### ISSUE TITLE
Boa Pedroca

### ISSUE THREAD

**Issue by JoaoSanchess** [PedroCoelhho/Fisiopar_base#1]
uehuaheuehuhek

**Comment by JoaoSanchess** [comment]
Porque quando eu tento colocar o arroba aparece o numero 2?

**Comment by PedroCoelhho** [comment]
SLA

**Comment by Galvyy** [comment]
222
aqui tbm LUL
![4a7](https://user-images.githubusercontent.com/42254114/44434390-3dbd9900-a581-11e8-9723-b9f18e5c6a93.jpg)
